# model
d_model: 512
d_k: 64
d_v: 64
d_ffn: 2048
n_heads: 8
n_layers: 2
dropout: 0.1
share_proj_weight: true
weighted_model: true
smoothing: 0.1

# train
lr: 0.0001
max_epochs: 6
batch_size: 256
max_src_seq_len: 100
max_trg_seq_len: 100
max_grad_norm: ~
optim_factor: 1
n_warmup_steps: 2000
log: ~
model_path: "../model.pkl"

# translate
max_trg_len: 12
beam_size: 2
translate_output: "../decode_output_ex.txt"


